### PR TITLE
Automated build with CircleCI and AppVeyor

### PR DESCRIPTION
**Pull request by stefanschererseal**
I've seen that version 0.1.7 now has a precompiled binary for Linux. Great!
@seal-mis and I worked out an automated build for Linux x64 and Windows x64 with CircleCI and AppVeyor. I send you our build yml files as a proposal.

That really helped us a lot compiling it without having both development environments, all can be done with CI servers in the cloud. We also updated and are now using your module with Node.js 4.2.1.

For [CircleCI](https://circleci.com/) you have to set an environment `SAPNWRFC_CRED` with `user:password` for the Download of sapcar.exe and the sapnwrfc SDK.

For [AppVeyor](http://www.appveyor.com/) it is very similar, but here the credential is added as encrypted string in `SAPNWRFC_CRED` into the appveyor.yml. I have marked the places. Another minor issue we had was that AppVeyor checks out a public repo without SSH key, so we also added an GitHub access token to the `appveyor.yml` so that AppVeyor can push the binary back into GitHub. So you have to set `ACCESS_TOKEN` in the appveyor.yml

The workflow looks like this. Someone changes code in master branch and then both CircleCI and AppVeyor start to compile the Linux and Windows binary and then pushes it back to GitHub.

Afterwards you could do a `git pull` and then `npm publish`.

After setting up the build servers you could add build badges to the README.md.

You can find a working example of all this in our fork at https://github.com/plossys/node-sapnwrfc with links to both build servers.

Both build servers can be used **without** a charge for open source repos.

If you are interested in setting this up and running and have questions, don't hesitate to contact me. We would love to see this in upstream as it lowers the barrier to contribute to your project.

### CODE REVIEW

**Comment by jdorner** [comment]
That's really nice! After some struggling I managed to get it going for both ci servers. Currently it will build 4 different Linux and a Windows binary. Additionally, some basic tests will also make sure that the binaries can be loaded by Node.js.

**Comment by stefanschererseal** [comment]
This is awesome!

And adding tests is really good. To add some real tests and skip them in Circle/AppVeyor we [worked around with the environment `CI`](https://github.com/plossys/node-rfc/blob/master/test/test.js#L60). But having an online SAP to run the tests against in a few seconds would really help in a feedback loop. How "open source" is SAP for this kind of tasks? :smile:

**Comment by stefanschererseal** [comment]
To create more compiled binaries for more node versions on AppVeyor we could have a look at the **Build matrix** feature: http://www.appveyor.com/docs/build-configuration#build-matrix

I haven't found such feature in CircleCI yet, but at Travis: http://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix

We could update the yml's to build and test and push the compiled version in one step, I think.

**Comment by jdorner** [comment]
Maybe there is a Chocolatey package for SAP NW trial versions?! :stuck_out_tongue:

The build matrix feature does work. One disadvantage is that it will generate commit spam as each binary will be pushed separately. Contrary to the Linux builds, the Windows binaries differ even if the source code has not been modified. Maybe I'll restrict recompilation to when a git tag has been pushed - at least for the master branch.

Tests: Good hint using the CI env variable for this!

**Comment by stefanschererseal** [comment]
Yes, Chocolatey :chocolate_bar: would be sweet! But I more thought of putting SAP into a Docker image :whale: so we could run it directly in the CircleCI build ;-) But probably too much resources needed.

For for standalone tests what about tools like Mountebank? 
* https://github.com/bbyars/mountebank
* http://www.mbtest.org

Capturing some TCP responses and replay them for tests. Just to check if parsing repsonses back to objects and tables etc. works fine.

**Comment by agebert** [comment]
I really like the effort of running automated builds and the binaries in
the npm package are very convenient. The drawback of putting the binaries
in the git repository too is that over time the git repository will
increase in size. Perhaps it is possible to put the binaries only into the
npm package.

**Comment by StefanScherer** [comment]
That might be an issue. As there are multiple build jobs (build matrix for different node version) and two build servers (linux + windows) are involved we would need some kind of artifact store for the current git commit hash. A github release might be the next free artifact store outside the git repo. But this makes the build a little more complex, but still possible with curl or powershell to post artifacts https://developer.github.com/changes/2013-09-25-releases-api/
Just an idea for now.

**Comment by jdorner** [comment]
After all the binaries are very small and Git saves binary diffs between commits. So I don't think size will be a problem in the forseeable future. On the other hand, I don't like having binaries in a source repository, too. Just out of principle :smile: For now I have restricted CI commits on Git tags only.

Maybe filing a release on Github would be a solution. I just don't know how this works out with the matrix build on AppVeyor... having a separate zip for each windows binary wouldn't be nice.

**Comment by StefanScherer** [comment]
@jdorner I have seen the [build matrix](https://github.com/jdorner/node-sapnwrfc/blob/master/gulpfile.js#L8) in the gulpfile.js. I think that could also be done on AppVeyor, what do you think? So there would be only one commit per platform with all node versions needed.
Then the windows build should also be faster as it only downloads the SDK once.

**Comment by jdorner** [comment]
The problem is, that nvm does not exist for Windows. There are several Windows ports of it, but installation could be tricky as they all require that node must not be installed before nvm is being installed. After all it would be much trial&error and it's really cumbersome on AppVeyor as you don't have any means to debug (like an SSH console).

**Comment by StefanScherer** [comment]
OK, I understand. 
Microsoft is working on a native port of OpenSSH ;-) 
But until then SSH means RDP, and you may enter the worker with RDP http://www.appveyor.com/docs/how-to/rdp-to-build-worker

I'm thinking of using the preinstalled node versions.

Perhaps adding some lines to the appveyor.yml could be a simple solution:

```yml
build_script:
  - set PATH=%PATH%;%SAPNWRFC_HOME%\lib
  - ps: Install-Product node 4.0.0 x64
  - npm install
  - ps: Install-Product node 4.1.2 x64
  - npm install
  - ps: Install-Product node 4.2.1 x64
  - npm install
  - ps: Install-Product node 5.0.0 x64
  - npm install
```

Or we put the steps inside the gulpfile.js to do the same as the `Install-Product node` command does. I think this just adjusts the PATH to point to one of the preinstalled `C:\Program Files\nodejs` versions.

**Pull request merged**
